/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivarRouteImport } from './routes/activar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvCodeRouteImport } from './routes/tv/$code'
import { Route as RoomCodeRouteImport } from './routes/room/$code'
import { Route as PlayCodeRouteImport } from './routes/play/$code'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivarRoute = ActivarRouteImport.update({
  id: '/activar',
  path: '/activar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvCodeRoute = TvCodeRouteImport.update({
  id: '/tv/$code',
  path: '/tv/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeRoute = RoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activar': typeof ActivarRoute
  '/admin': typeof AdminRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/play/$code': typeof PlayCodeRoute
  '/room/$code': typeof RoomCodeRoute
  '/tv/$code': typeof TvCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activar': typeof ActivarRoute
  '/admin': typeof AdminRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/play/$code': typeof PlayCodeRoute
  '/room/$code': typeof RoomCodeRoute
  '/tv/$code': typeof TvCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activar': typeof ActivarRoute
  '/admin': typeof AdminRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/play/$code': typeof PlayCodeRoute
  '/room/$code': typeof RoomCodeRoute
  '/tv/$code': typeof TvCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activar'
    | '/admin'
    | '/landing'
    | '/login'
    | '/api/stripe-webhook'
    | '/play/$code'
    | '/room/$code'
    | '/tv/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activar'
    | '/admin'
    | '/landing'
    | '/login'
    | '/api/stripe-webhook'
    | '/play/$code'
    | '/room/$code'
    | '/tv/$code'
  id:
    | '__root__'
    | '/'
    | '/activar'
    | '/admin'
    | '/landing'
    | '/login'
    | '/api/stripe-webhook'
    | '/play/$code'
    | '/room/$code'
    | '/tv/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivarRoute: typeof ActivarRoute
  AdminRoute: typeof AdminRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  PlayCodeRoute: typeof PlayCodeRoute
  RoomCodeRoute: typeof RoomCodeRoute
  TvCodeRoute: typeof TvCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activar': {
      id: '/activar'
      path: '/activar'
      fullPath: '/activar'
      preLoaderRoute: typeof ActivarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$code': {
      id: '/tv/$code'
      path: '/tv/$code'
      fullPath: '/tv/$code'
      preLoaderRoute: typeof TvCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code': {
      id: '/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof RoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivarRoute: ActivarRoute,
  AdminRoute: AdminRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  PlayCodeRoute: PlayCodeRoute,
  RoomCodeRoute: RoomCodeRoute,
  TvCodeRoute: TvCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
